# Generated by Django 4.0.6 on 2022-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0005_rename_cereal_dish_appetizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='pix.jpg', null=True, upload_to='food'),
        ),
    ]
