# Generated by Django 4.0.6 on 2022-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0008_showcase_remove_dish_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
